### ISSUE TITLE
Unable to Seek

### ISSUE THREAD

**Issue by arulapj** [minoscc/codec-as3#1]
Hi,

You have done a wondeful job, very much thanks for your contribution,

But i am unable to seek when loaded using your library

/* loading code */ 

songBytes.position = 0;
var mp4:Mp4Codec = new Mp4Codec();
mp4.decode(songBytes);
var flvbytes:ByteArray = new FlvCodec().encode(mp4);

netSt.play(null);
netSt.appendBytesAction(NetStreamAppendBytesAction.RESET_BEGIN); 
netSt.appendBytes(flvbytes);

but when seeking there seems to be no keyframes in the metadata, due to this i am unable to seek to the position. 

Can please explain how to do it, if its there.. or if not can you please add this feature

PS: also we are unable to load the mp4 which are hinted using mp4box which adds hint to the file, i am getting "index out of bound" error

**Comment by minoscc** [comment]
yes,  no keyframe list in the metadata, I will add in the near future.
and you are try to transcode mp4 to flv? it looks a song?

**Comment by arulapj** [comment]
yes, its a song.. its mp4 (aac) to flv..  can u please tell us how we can seek without keyframe

**Comment by minoscc** [comment]
1. use `play('mp4-url');`.
2. if you want to use `appendBytes()`. you must append rest-bytes(with codec specs and repackage) again when you seek. [api doc](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/NetStream.html#seek())

**Comment by arulapj** [comment]
hi 
sorry for bothering you again

is there any possibility to append rest-bytes without knowing the keyframe or position,  

netSt.appendBytesAction(NetStreamAppendBytesAction.RESET_SEEK);					
					songBytes.position = seekPos;					
					var bytes:ByteArray = new ByteArray();
					songBytes.readBytes(bytes);
					netSt.appendBytes(bytes);					
					netSt.resume();		

this is the code i am trying to use seek, but as you see i am unable to get the seekPos which is added using keyframes timestamp and postion..

**Comment by arulapj** [comment]
Thanks a lot for your help,

used 	netSt.client.onSeekPoint = this.onSeekPoint; and keyframes are generated on fly.. 

now i am able to get the timestamp and position
